### ISSUE TITLE
Error: Cannot find module ‘stylus’

### ISSUE THREAD

**Issue by mthompson** [shenshuai89/vueGentelella#1]
Upon running `npm run dev` you will currently experience the following error:
`Error: Cannot find module ‘stylus’`

Interim Solution:
`npm install stylus --save-dev`

Permanent solution:
maintainer, please update `package.json` to reflect stylus dependency

Thanks for all the great work you've done thus far!

**Comment by shenshuai89** [comment]
Thank you!
