### ISSUE TITLE
关于下拉菜单：不能使用gentelella原来的js文件吗

### ISSUE THREAD

**Issue by DivingPigy** [shenshuai89/vueGentelella#3]
菜单下拉方面您是通过App.vue的script模块进行控制的。

菜单效果：
![default](https://user-images.githubusercontent.com/26334368/42300736-7cdbd92e-8044-11e8-814e-5c72e9907073.png)

代码实现：
`    methods: {
      toggleShow(n){
        var vm = this;
        if (vm.lists[n].show == true) {
          vm.lists[n].show = !vm.lists[n].show;
        } else {
          for (var i = 0; i < 5; i++) { // close all boxes
            vm.lists[i].show = false;
          }
          vm.lists[n].show = true;
        }
      }
    }`

请问可以引入gentelella写好的下拉菜单的js脚本吗？

**Comment by shenshuai89** [comment]
可以啊，不过那样会麻烦的

**Comment by DivingPigy** [comment]
import “gentelella/...../js/custom.js”  这种语法引入js可以吗 @shenshuai89

**Comment by shenshuai89** [comment]
是的，前提是js文件要先有export变量

**Comment by DivingPigy** [comment]
好的 @shenshuai89 (๑•̀ㅂ•́)و✧
